language: python
python: 2.7
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gettext
install:
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg 
  - bin/buildout -c travis.cfg -N
script:
  - bin/i18n cpskin
  - bin/i18n plone
  - msgfmt -o cpskin/locales/locales/fr/LC_MESSAGES/cpskin.mo cpskin/locales/locales/fr/LC_MESSAGES/cpskin.po
notifications:
  email:
    recipients:
      - devel@lists.affinitic.be
      - devs@imio.be
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.org#imio"
    on_success: change
    on_failure: always
